---
openapi: 3.0.1
info:
  title: API IMC V1
  version: v1
paths:
  "/imcs":
    post:
      summary: Creates a pet
      tags:
      - Imcs
      parameters: []
      responses:
        '201':
          description: imc calculado
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                height:
                  type: float
                weight:
                  type: float
              required:
              - height
              - weight
servers:
- url: https://www.softwaremedico.com
  variables:
    defaultHost:
      default: www.softwaremedico.com
